/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.26.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { ActiveThreshold, ActiveThresholdResponse, Addr, InfoResponse, Boolean, TotalPowerAtHeightResponse, VotingPowerAtHeightResponse } from "./CwFundDistributor.types";
import { BaseClient, DeliverTxResponse } from "./Base.client";
export interface CwFundDistributorReadOnlyInterface {
  contractAddress: string;
  stakingContract: () => Promise<Addr>;
  activeThreshold: () => Promise<ActiveThresholdResponse>;
  votingPowerAtHeight: ({
    address,
    height
  }: {
    address: string;
    height?: number;
  }) => Promise<VotingPowerAtHeightResponse>;
  totalPowerAtHeight: ({
    height
  }: {
    height?: number;
  }) => Promise<TotalPowerAtHeightResponse>;
  dao: () => Promise<Addr>;
  info: () => Promise<InfoResponse>;
  tokenContract: () => Promise<Addr>;
  isActive: () => Promise<Boolean>;
}
export interface CwFundDistributorInterface extends CwFundDistributorReadOnlyInterface {
  contractAddress: string;
  sender: string;
  updateActiveThreshold: ({
    newThreshold
  }: {
    newThreshold?: ActiveThreshold;
  }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
}
export class CwFundDistributorClient extends BaseClient {
  sender: string;
  contractAddress: string;

  constructor(execute: any, sender: string, contractAddress: string) {
    super(execute);
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.updateActiveThreshold = this.updateActiveThreshold.bind(this);
  }

  updateActiveThreshold = async ({
    newThreshold
  }: {
    newThreshold?: ActiveThreshold;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<DeliverTxResponse> => {
    return await super.execute(this.sender, this.contractAddress, {
      update_active_threshold: {
        new_threshold: newThreshold
      }
    }, fee, memo, funds);
  };
}