import '@mantine/core/styles.css'
import { ColorSchemeScript } from '@mantine/core'
import { Metadata } from 'next'
import Providers from '../Providers/Providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <head>
        <meta name='theme-color' content='#000000' />
        <ColorSchemeScript />
      </head>

      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
