name: Build and deploy to production
on:
  push:
    branches:
      - main

env:
  NODE_OPTIONS: '--max_old_space_size=8192'
  NEXT_PUBLIC_BLOCK_SYNC_GRAPHQL: ${{ vars.REACT_APP_BLOCK_SYNC_GRAPHQL }}
  NEXT_PUBLIC_CHAIN_ID: ${{ vars.REACT_APP_CHAIN_ID }}
  NEXT_PUBLIC_BLOCK_SYNC_URL: ${{ vars.REACT_APP_BLOCK_SYNC_URL }}
  NEXT_PUBLIC_BLOCK_SCAN_URL: ${{ vars.REACT_APP_BLOCK_SCAN_URL }}
  NEXT_PUBLIC_GAIA_URL: ${{ vars.REACT_APP_GAIA_URL }}
  NEXT_PUBLIC_RPC_URL: ${{ vars.REACT_APP_RPC_URL }}
  NEXT_PUBLIC_PDS_URL: ${{ vars.REACT_APP_PDS_URL }}
  NEXT_PUBLIC_CONFIG_APP: ${{ vars.REACT_APP_CONFIG_APP }}
  NEXT_PUBLIC_CLIENT_URL: ${{ vars.REACT_APP_CLIENT_URL }}
  NEXT_PUBLIC_IXO_WORLD_ORIGIN: ${{ vars.REACT_APP_IXO_WORLD_ORIGIN }}
  NEXT_PUBLIC_KYC_LINK: ${{ vars.REACT_APP_KYC_LINK }}
  NEXT_PUBLIC_ASSISTANT_URL: ${{ vars.REACT_APP_ASSISTANT_URL }}
  NEXT_PUBLIC_ENTITY_VERSION: ${{ vars.REACT_APP_ENTITY_VERSION }}
  NEXT_PUBLIC_ENTITY_PAGE_VERSION: ${{ vars.REACT_APP_ENTITY_PAGE_VERSION }}
  NEXT_PUBLIC_EMBEDLY_KEY: ${{ vars.REACT_APP_EMBEDLY_KEY }}
  NEXT_PUBLIC_GOOGLE_API_KEY: ${{ vars.REACT_APP_GOOGLE_API_KEY }}
  NEXT_PUBLIC_FEE_PER_CLAIM_FEE: ${{ vars.REACT_APP_FEE_PER_CLAIM_FEE }}
  NEXT_PUBLIC_FEE_PER_EVALUATION: ${{ vars.REACT_APP_FEE_PER_EVALUATION }}
  NEXT_PUBLIC_FEE_OVERHEAD: ${{ vars.REACT_APP_FEE_OVERHEAD }}
  NEXT_PUBLIC_RELAYER_NODE: ${{ vars.REACT_APP_RELAYER_NODE }}
  NEXT_PUBLIC_MULTI_CALL_CONTRACT_ADDRESS: ${{ vars.REACT_APP_MULTI_CALL_CONTRACT_ADDRESS }}
  NEXT_PUBLIC_CONFIG_ASSETLIST_URL: ${{ vars.REACT_APP_CONFIG_ASSETLIST_URL }}
  NEXT_PUBLIC_CONFIG_EXCHANGE_URL: ${{ vars.REACT_APP_CONFIG_EXCHANGE_URL }}
  NEXT_PUBLIC_CONFIG_RELAYER_URL: ${{ vars.REACT_APP_CONFIG_RELAYER_URL }}
  NEXT_PUBLIC_CONFIG_SCHEMA_URL: ${{ vars.REACT_APP_CONFIG_SCHEMA_URL }}
  NEXT_PUBLIC_CUSTOM_THEME_URL: ${{ vars.REACT_APP_CUSTOM_THEME_URL }}
  NEXT_PUBLIC_ASSISTANT_API_KEY: ${{ vars.REACT_APP_ASSISTANT_API_KEY }}
  NEXT_PUBLIC_ALGOLIA_APP_ID: ${{ vars.REACT_APP_ALGOLIA_APP_ID }}
  NEXT_PUBLIC_ALGOLIA_SEARCH_KEY: ${{ vars.REACT_APP_ALGOLIA_SEARCH_KEY }}
  NODE_ENV: ${{ vars.NODE_ENV }}

jobs:
  build-and-deploy-launchpad-ixo-world:
    runs-on: ubuntu-latest
    environment: prod
    outputs:
      url: ${{ steps.launchpad_ixo_world_prod_deploy.outputs.NETLIFY_LIVE_URL }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.18.2' # Node Version

      - name: Install Dependencies
        run: yarn

      - name: Build
        env:
          NODE_ENV: production
        run: |
          export NODE_OPTIONS="--max_old_space_size=8192"
          yarn build  # Build Script

      - name: Deploy to launchpad.ixo.world
        uses: netlify/actions/cli@master
        id: launchpad_ixo_world_prod_deploy
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: 1f94cb83-da26-4709-ab97-ccb75c0068e9 # Replace with your Netlify Site ID
        with:
          args: deploy --dir=out --prod # Update --dir with the directory of your build output

  build-and-deploy-refi-ixo-earth:
    runs-on: ubuntu-latest
    environment: prod
    outputs:
      url: ${{ steps.refi_ixo_earth_prod_deploy.outputs.NETLIFY_LIVE_URL }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.18.2' # Node Version

      - name: Install Dependencies
        run: yarn

      - name: Build
        env:
          NEXT_PUBLIC_RELAYER_NODE: did:ixo:entity:50a336298abaaaa248d08d794b2e6231
          NEXT_PUBLIC_CONFIG_ASSETLIST_URL: https://raw.githubusercontent.com/ixofoundation/ixo-webclient/dev/configs/refi/asset-list.json
          NEXT_PUBLIC_CONFIG_EXCHANGE_URL: https://raw.githubusercontent.com/ixofoundation/ixo-webclient/dev/configs/refi/exchange.json
          NEXT_PUBLIC_CONFIG_RELAYER_URL: https://raw.githubusercontent.com/ixofoundation/ixo-webclient/dev/configs/refi/app-config.json
          NEXT_PUBLIC_CONFIG_SCHEMA_URL: https://raw.githubusercontent.com/ixofoundation/ixo-webclient/dev/configs/refi/config.json
          NEXT_PUBLIC_CUSTOM_THEME_URL: https://raw.githubusercontent.com/ixofoundation/ixo-webclient/dev/configs/refi/theme.json
          NODE_ENV: production
        run: |
          export NODE_OPTIONS="--max_old_space_size=8192"
          yarn build  # Build Script

      - name: Deploy to refi.ixo.earth
        uses: netlify/actions/cli@master
        id: refi_ixo_earth_prod_deploy
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: 982884ec-0cf4-4280-8d73-6ec9ce9a321d # Replace with your Netlify Site ID

        with:
          args: deploy --dir=out --prod # Update --dir with the directory of your build output

  build-and-deploy-platform-impacts-ai:
    runs-on: ubuntu-latest
    environment: prod
    outputs:
      url: ${{ steps.platform_impacts_ai_prod_deploy.outputs.NETLIFY_LIVE_URL }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.18.2' # Node Version

      - name: Install Dependencies
        run: yarn

      - name: Build
        env:
          NEXT_PUBLIC_RELAYER_NODE: did:ixo:entity:72a27013b1d2f9c3561145e4a424778a
          NEXT_PUBLIC_CONFIG_ASSETLIST_URL: https://raw.githubusercontent.com/ixofoundation/ixo-webclient/dev/configs/impacts-ai/asset-list.json
          NEXT_PUBLIC_CONFIG_EXCHANGE_URL: https://raw.githubusercontent.com/ixofoundation/ixo-webclient/dev/configs/impacts-ai/exchange.json
          NEXT_PUBLIC_CONFIG_RELAYER_URL: https://raw.githubusercontent.com/ixofoundation/ixo-webclient/dev/configs/impacts-ai/app-config.json
          NEXT_PUBLIC_CONFIG_SCHEMA_URL: https://raw.githubusercontent.com/ixofoundation/ixo-webclient/dev/configs/impacts-ai/config.json
          NEXT_PUBLIC_CUSTOM_THEME_URL: https://raw.githubusercontent.com/ixofoundation/ixo-webclient/dev/configs/impacts-ai/theme.json
          NODE_ENV: production
        run: |
          export NODE_OPTIONS="--max_old_space_size=8192"
          yarn build  # Build Script

      - name: Deploy to platform.impacts.ai
        uses: netlify/actions/cli@master
        id: platform_impacts_ai_prod_deploy
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: 1f5e8c66-5e62-42ed-9a55-1650bbb1fe43 # Replace with your Netlify Site ID

        with:
          args: deploy --dir=out --prod # Update --dir with the directory of your build output

  notify-slack:
    needs: [build-and-deploy-launchpad-ixo-world, build-and-deploy-refi-ixo-earth, build-and-deploy-platform-impacts-ai]
    runs-on: ubuntu-latest
    steps:
      - name: Send URLs to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          URL1=${{ needs.build-and-deploy-launchpad-ixo-world.outputs.url }}
          URL2=${{ needs.build-and-deploy-refi-ixo-earth.outputs.url }}
          URL3=${{ needs.build-and-deploy-platform-impacts-ai.outputs.url }}

          MESSAGE="Deployment to production environment for launchpad.ixo.world: $URL1\nDeployment to production environment for refi.ixo.earth: $URL2\nDeployment to production environment for platform.impacts.ai: $URL3\n"

          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"$MESSAGE\"}" $SLACK_WEBHOOK_URL
